In [1]:
import numpy as np

２乗和誤差  
$
    \large{E = \frac{1}{2}\sum_k(y_k-t_k)^2}
$

In [2]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

In [3]:
def sum_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)

In [4]:
sum_squared_error(np.array(y), np.array(t))

0.09750000000000003

交差エントロピー誤差  
$
    \large{E = -\sum_{k}t_k\log{y_k}}
$

In [5]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [6]:
cross_entropy_error(np.array(y), np.array(t))

0.510825457099338

ミニバッチ学習に対応した交差エントロピー誤差  
$
    E = \large{-\frac{1}{N}\sum_{n}\sum_{k}t_{nk}\log{y_{nk}}}
$  

In [41]:
from keras.datasets import mnist

In [42]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [43]:
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [44]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [45]:
train_labels_tmp = train_labels.reshape(-1, 1)

In [46]:
train_labels_tmp

array([[5],
       [0],
       [4],
       ...,
       [5],
       [6],
       [8]], dtype=uint8)

In [47]:
train_images = train_images.reshape(60000, 784)
test_images = test_images.reshape(10000, 784)

In [48]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(categories="auto", sparse=False, dtype=np.float32)
onehot_train_labels = enc.fit_transform(train_labels_tmp)


In [49]:
print(train_images.shape)
print(onehot_train_labels.shape)

(60000, 784)
(60000, 10)


In [50]:
train_size = train_images.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = train_images[batch_mask]
t_batch = onehot_train_labels[batch_mask]

In [51]:
batch_mask

array([28488, 10117, 17309,  6399, 30188, 43891, 49266, 16591, 42493,
       49477])

In [52]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [53]:
cross_entropy_error(train_images, onehot_train_labels)

ValueError: operands could not be broadcast together with shapes (60000,10) (60000,784) 

In [54]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [55]:
cross_entropy_error(train_images, train_labels)

16.118095650958313

In [ ]:
train_labels